name: UI and Unit Tests
on:
  push:
    branches: [ develop ]
    paths:
      - '!README.md'
      - '!*.yml'
      - '!art/**'
      - '!build.gradle'
  pull_request:
    branches: [ develop ]
jobs:
  ui-and-unit-tests-app:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: run Example app tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew ktlint test app:connectedDebugAndroidTest
      - name: 'Publish App Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'app-test-report'
          path: app/build/reports/androidTests/*