name: TEST - GitHub Tag and Release

on:
  push:
    branches: [ release_note_output ] #[ release/* ]
#    paths:
#      - '!README.md'
#      - '!art/**'
#      - '!*.yml'
#      - '!build.gradle'

jobs:
  build:
    name: Create Release and tag
    runs-on: macos-latest
    env:
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      CHANGELOG_PATH: "CHANGELOG.md"
      RELEASE_NOTE_PATH: "release_note.txt"
      README_PATH: "README.md"
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: (MMMM, DD, YYYY)
      - name: Set version lib into VERSION_NAME variable
        run: |
          ./gradlew app:versionTxt
          echo "VERSION_NAME=$(cat app/version.txt)" >> $GITHUB_ENV
      - name: Update CHANGELOG.md
        run: |
          ./gradlew app:changeLogUpdate
      - name: Update README.md
        run: |
          ./gradlew app:replaceInFile
      - name: Read Release Note
        id: release_note
        run: |
          echo =====================================
          echo 'RELEASE_NOTE<<EOF' >> $GITHUB_ENV
          cat release_note.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo =====================================
      - name: Set the value
        id: step_one
        run: |
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          curl https://httpbin.org/json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        run: |
          echo ${{ steps.release_note.outputs.content }}
          echo ${{ steps.test_output.outputs.content }}
          echo ${{ env.JSON_RESPONSE }}
          echo ${{ env.RELEASE_NOTE }}
