name: TEST - GitHub Tag and Release

on:
  push:
    branches: [ add-commit-push-1_disabled ] #[ release/* ]
    paths:
      - '!README.md'
      - '!*.yml'
      - '!art/**'
      - '!build.gradle'
jobs:
  build:
    name: Create Release and tag
    runs-on: macos-latest
    env:
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add, commit and push CHANGELOG.md and README.md
        env:
          GRADLE_PROPERTIES: "app/gradle.properties"
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          CHANGELOG_PATH: "CHANGELOG.md"
          RELEASE_NOTE_PATH: "release_note.txt"
        run: |
          ./gradlew app:changeLogUpdate -P releaseNotePath=$RELEASE_NOTE_PATH -P changeLogPath=$CHANGELOG_PATH
          ./gradlew app:addCommitPush -P files=$CHANGELOG_PATH:$README_PATH
#      - name: Get current time
#        uses: 1466587594/get-current-time@v2
#        id: current-time
#        with:
#          format: (MMMM, DD, YYYY)
#      - name: Set version lib into VERSION_NAME variable
#        run: |
#          ./gradlew app:versionTxt
#          echo "VERSION_NAME=$(cat app/version.txt)" >> $GITHUB_ENV
#      - name: Update CHANGELOG.md
#        env:
#          CHANGELOG_PATH: "CHANGELOG.md"
#          RELEASE_NOTE_PATH: "release_note.txt"
#        run: |
#          ./gradlew app:changeLogUpdate -P releaseNotePath=$RELEASE_NOTE_PATH -P changeLogPath=$CHANGELOG_PATH
#      - name: Update README.md
#        env:
#          README_PATH: "README.md"
#        run: |
#          ./gradlew app:readmeUpdate
#      - name: Add, commit and push CHANGELOG.md and README.md
#        env:
#          README_PATH: "README.md"
#          CHANGELOG_PATH: "CHANGELOG.md"
#        run: |
#          ./gradlew app:addCommitPush -P files=$CHANGELOG_PATH:$README_PATH -P user_name=ciriti@gmail.com -P user_email=GitAction
#      - name: Read Release Note
#        id: release_note
#        run: echo "RELEASE_NOTE=$(cat $RELEASE_NOTE_PATH)" >> $GITHUB_ENV
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          CURRENT_TIME: "${{ steps.current-time.outputs.formattedTime }}"
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: v${{ env.VERSION_NAME }}
#          release_name: v${{ env.VERSION_NAME }}
#          body: |
#            ## ${{ env.VERSION_NAME }} ${{ env.CURRENT_TIME }}
#            ${{ env.RELEASE_NOTE }}
#          draft: false
#          prerelease: false
#      - name: Bintray upload artifact
#        env:
#          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
#          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
#        run: |
#          ./gradlew okhttp-socket-ext:bintrayUpload